name: Build and Deploy .NET Framework Web API to Azure

on:
  push:
    branches:
      - main   # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: windows-latest   # 👈 Required for .NET Framework builds

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore GlobaHr-SendEmail-API.sln   # 👈 replace with your solution file

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

# Build and publish using MSBuild with publish profile
- name: Build with MSBuild
  run: msbuild GlobaHr-SendEmail-API.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}\WebApp.zip"


      # Deploy to Azure Web App using Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "GlobalHr-SendAPI"   # 👈 replace with your Azure App Service name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}\bin\Release