name: Build and Deploy .NET App to Azure WebApp

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # change if using 6.0 / 7.0 / framework

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      # 🔐 Login with SPN (no Basic Auth needed)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🚀 Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GlobalHr-SendAPI'   # replace with your App Service name
          slot-name: 'production'
          package: ./publish
