name: Build and Deploy .NET Framework 4.6 App to Azure WebApp

on:
  push:
    branches:
      - main   # change if using a different branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3. Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore GlobaHr-SendEmail-API.sln

      # 5. Build using MSBuild (not dotnet build!)
      - name: Build with MSBuild (detailed logs)
  	run: msbuild GlobaHr-SendEmail-API.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:detailed

      # 6. Publish to a folder
      - name: Publish with MSBuild
        run: msbuild GlobaHr-SendEmail-API.sln /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl="${{ github.workspace }}\\publish" /p:Configuration=Release

      # 7. Create deployment ZIP
      - name: Create deployment package
        run: powershell Compress-Archive -Path "${{ github.workspace }}\\publish\\*" -DestinationPath "${{ github.workspace }}\\publish.zip" -Force

      # 8. Upload artifact (optional)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-framework-app
          path: ./publish.zip

      # 9. Deploy package to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GlobalHr-SendAPI'   # 👈 your App Service name
          package: ${{ github.workspace }}\\publish.zip
