name: Build and Deploy .NET Framework Web API to Azure

on:
  push:
    branches:
      - main   # change if using a different branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3. Install .NET Framework 4.6.1 Developer Pack (needed for GitHub runners)
      - name: Install .NET Framework 4.6.1 Developer Pack
        run: |
          choco install netfx-4.6.1-devpack -y

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore GlobaHr-SendEmail-API/GlobaHr-SendEmail-API.csproj

      # 5. Build with MSBuild
      - name: Build with MSBuild
        run: msbuild GlobaHr-SendEmail-API/GlobaHr-SendEmail-API.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=Package `
            /p:PackageAsSingleFile=true `
            /p:SkipInvalidConfigurations=true `
            /p:PackageLocation="WebApp.zip"

      # 6. Upload build artifact (optional but useful)
      - name: Upload WebApp artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApp
          path: WebApp.zip
