name: Build and Deploy .NET Framework 4.6 App to Azure WebApp

on:
  push:
    branches:
      - main   # change if using a different branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3. Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore GlobaHr-SendEmail-API.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      # 7. Deploy package to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GlobalHr-SendAPI'   # 👈 replace with your App Service name
          package: ${{ github.workspace }}\\output\\*.zip
