name: Build and Deploy .NET Framework App to Azure WebApp

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add MSBuild to PATH
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Add NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore GlobaHr-SendEmail-API.sln

      # Build with MSBuild
      - name: Build with MSBuild
        run: msbuild GlobaHr-SendEmail-API.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}\\output"

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy package to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GlobalHr-SendAPI'   # Replace with your App Service name
          package: ${{ github.workspace }}\\output\\*.zip
